# Generated by Django 3.0.4 on 2020-06-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['type']},
        ),
    ]
