# Generated by Django 3.0.4 on 2020-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('compositor', models.CharField(max_length=200)),
                ('screenwriter', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('adult', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('movie', models.ManyToManyField(to='movie.Movie')),
            ],
        ),
    ]
