# Generated by Django 3.0.4 on 2020-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='news',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Movie'),
        ),
    ]
