# Generated by Django 3.0.4 on 2020-06-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='hall_name',
            field=models.CharField(default='First hall', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ManyToManyField(blank=True, through='table.TableReservation', to='table.Table'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.Reservation'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.Table'),
        ),
    ]
